routes/web.php
     /***********ruta resource para los productos juridicos*************/
     Route::get('DatosAccionista/{id}/eliminarAccionista','AccionistaController@eliminarAccionista');
     Route::resource('RegisMercantil','RegisMercantilController');
     Route::resource('DatosAcceso','DatosAccesoController');
    Route::resource('DocumentosSoportes','DocumentosSoportesController');
     Route::resource('detSolicitud','DetProdSolicitudController');
     Route::get('/planillaEr', [
         'uses' => 'PdfController@planillaEr',
     ]);
     Route::get('/planillaTecno', [
         'uses' => 'PdfController@planillaTecno',
       ]);
     Route::get('/PlanillaDvd', [
         'uses' => 'PdfController@planillaDvd',

     ]);
      Route::get('/PlanillaDvdDesestimiento', [
         'uses' => 'PdfController@planillaDvdDes',

     ]);
    Route::get('/PlanillaDvdNotaDebito', [
         'uses' => 'PdfController@planillaNotaD',

     ]);
    Route::get('/PlanillaDvdNotaDebitoDesestimiento', [
         'uses' => 'PdfController@planillaDvdDesND',

     ]);
    Route::get('/PlanillaConsigDoc', [
         'uses' => 'PdfController@PlanillaConsigDoc',

     ]);

    /***********Ruta para obtener los paises ajax *************/
    Route::get('ajax/paises/all',['uses' => 'AjaxGenPaises@listarTodo']);
    Route::get('ajax/sectoreconomico',['uses' => 'AjaxGenSectorEconomico@listar']);
    Route::get('ajax/destinoinversion',['uses' => 'AjaxGenDestinoInversion@listar']);
    /***********Ruta resource para declaracion jurada de origen *************/
    Route::POST('ListaDeclaracionJO/storeComercializador',[
        'uses'=>'ListaDeclaracionJOController@storeComercializador',
        'as'=> 'ListaDeclaracionJO.storeComercializador'
    ]);
    Route::resource('ListaDeclaracionJO','ListaDeclaracionJOController');
    Route::get('DeclaracionJO/pdf',[
        'uses'=>'DeclaracionJOController@pdf',
        'as' => "DeclaracionJO.pdf"
        ]);

    Route::resource('DeclaracionJO','DeclaracionJOController');
    /** Ruta resource para la construccion de las planillas **/
    Route::resource('DJOPlanilla2','DJOPlanilla2Controller');
    Route::resource('DJOPlanilla3','DJOPlanilla3Controller');
    Route::resource('DJOPlanilla4','DJOPlanilla4Controller');
    Route::resource('DJOPlanilla5','DJOPlanilla5Controller');
    Route::resource('DJOPlanilla6','DJOPlanilla6Controller');
    /***********ruta resource para el certificado de origen *************/
    Route::resource('CertificadoOrigen','CertificadoController');
    Route::get('CertificadoOrigen/{id}/eliminarRegistroProd','CertificadOrigenController@deleteProducto');
    Route::get('CertificadoOrigen/{id}/eliminarRegistroCriterio','CertificadOrigenController@deleteCriterio');
    /********CAMBIO DE CONTRASEÑA**************/
    Route::resource('CambioContrasena','CambioContrasenaController');
    /********CAMBIO PREGUNTA DE SEGURIDAD**************/
    /*Route::get('/cambioPreguntaSeguridad', function(){

        return view('usuario.forms.cambioPreguntaSeguridad')->with('titulo','Cambio de Pregunta de Seguridad')->with('descripcion','Datos de Pregunta de Seguridad');

    });*/

    /*Route::post('/actualizarempresa', [
        'uses' => 'HomeController@accionform1'
    ]);
    */
    /********REGISTRO DE CONSIGNATARIO**************/
    Route::resource('consignatario','RegistroConsignatarioController');
    /********REGISTRO DE AGENTE ADUANAL**************/
    Route::resource('AgenteAduanal','AgenteAduanalController');
    /********REGISTRO DE DUA**************/
    Route::resource('Dua', 'DuaController');
    /********REGISTRO DE FACTURA**************/
    /********CAMBIO PREGUNTA DE SEGURIDAD*******/
     Route::resource('CambioPregunta','CambioPreSegController');
   /****************Registro de Factura -Productos***************/
    Route::resource('factura','GenFacturaController');
    Route::resource('productos','DetProdFacturaController');
    Route::get('productos/{id}/eliminar','DetProdFacturaController@eliminar');
    /******************** Routes Facturas -Tecnologia ****************************/
    Route::get('productos_tecno/{id}/eliminar','DetProdTecnologiaController@eliminar');
    Route::get('verificarFac','TipoSolicitudController@verificarFac');
    Route::resource('productos_tecno','DetProdTecnologiaController');
    /********REGISTRO DE PERMISO**************/
    Route::resource('Permisos','PermisoController');
    Route::resource('ProdutPermisos','ProdutPermisosController');
    Route::get('ProdutPermisos/{id}/eliminar','ProdutPermisosController@eliminar');
    /*****************************************/
     /********REGISTRO DE Nota de Credito**************/

    Route::resource('NCredito','NCreditoController');

     Route::get('/facturaNC', [
         'uses' => 'NCreditoController@facturaNC',

     ]);

    /************************************************/
    /********REGISTRO DE Nota de Debito**************/

    Route::resource('NDebito','NdebitoController');

     Route::get('/facturaND', [
         'uses' => 'NdebitoController@facturaND',

     ]);
    /********ANTICIPO DE EXPORTACION**************/
    /*Route::get('/datosempresa', function(){



    /********ANTICIPO DE EXPORTACION**************/
    Route::resource('Anticipo','GenAnticipoController');


    /********REGISTRO DE EXPORTACION**************/
    Route::resource('SolicitudER','TipoSolicitudController');
    Route::resource('FacturaSolicitud','FacturaSolicitudController');
    Route::get('FacturaSolicitud/{id}/eliminar','FacturaSolicitudController@eliminar');
    Route::resource('','FacturaSolicitudController');
    Route::get('factura-solicitud/{id}/delete-er', 'FacturaSolicitudController@deleteEr')->name('factura-solicitud.delete-er');
   


    /********REGISTRO DE EXPORTACION Financiamiento Solicitud**************/
    Route::resource('FinanciamientoSolicitud','FinancSolicitudController');
    Route::get('FinanciamientoSolicitud/{id}/edit','FinancSolicitudController@edit');

    Route::resource('productos_export','ProductosController');
    Route::get('productos_export/{id}/eliminar','ProductosController@eliminar');
    Route::get('productos_export/{id}/editar','ProductosController@editar');
    Route::POST('actualizar',[
        'uses'=>'ProductosController@actualizar',
        'as'=> 'productos_export_edit.actualizar'
    ]);


    /******************************************************************************/

    /************************Registro de DVD**************************************/

    Route::resource('DvdSolicitud','GenDVDSolicitudController');
    Route::resource('ListaVenta','ListaVentaController');
    Route::resource('VentaSolicitud','VentaSolicitudController');





    /**************************Documentos de DVD*************************************/

    Route::resource('DocumentosDVD','DocumentosDVDController');
    Route::get('documentos-dvd/{id}/delete-dvd', 'DocumentosDVDController@deleteDvd')->name('documentos-dvd.delete-dvd');


    //Ruta para  Eliminar Lista dinamica Doc 2 y 4
    Route::get('DocumentosDVD/{id}/eliminarDocDvd','DocumentosDVDController@eliminarDocDvd');



    Route::resource('ListaVentaND','ListaVentaNDController');

    Route::resource('VentanND','VentaNDController');


    Route::resource('DvdSolicitudND','ListaVentaNDController');



    /**************************Documentos de DVD*************************************/

    Route::resource('DocumentosDvdND','DocumentosDvdNDController');


    //Ruta para  Eliminar Lista dinamica Doc 2 y 4
    Route::get('DocumentosDvdND/{id}/eliminarDocND','DocumentosDvdNDController@eliminarDocND');






    /*************************Reportar dudas o Problemas***************************/
    Route::resource('Dudas','DudasController');
    
    Route::post('Dudas/delete/{id}',[
        'uses' => 'DudasController@destroy'
    ]);

    Route::put('Dudas/update/{id}',[
        'uses' => 'DudasController@update'
    ]);

    Route::get('Dudas/{gen_asistencia_usuario_id}',[
        'uses' => 'DudasController@edit'
    ]);

    /*inversionista extranjera*/
    Route::resource('BandejaInversionista','InversionistaExtController');//

     Route::POST('FormInversionista',[
        'uses'=>'InversionistaExtController@RedireccionarForm',
        'as'=> 'BandejaInversionista.FormInversionista'
    ]);
     //Para cuando falla el Vali
      Route::get('FormInversionista',[
        'uses'=>'InversionistaExtController@RedireccionarForm',
        'as'=> 'BandejaInversionista.FormInversionista'
    ]);



    Route::get('BandejaInversionista/ActividadEcoInversionista/{id}', [
        'uses' => 'InversionistaExtController@ActividadEcoEmpnIvert'
    ]);





    //Ruta para  Eliminar Lista dinamica Doc 2 y 4
    Route::get('BandejaInversionista/{id}/eliminarSoporte2','InversionistaExtController@eliminarSoporte');

    /////////////////////////////////////////////////////////////

      //Ruta para  Eliminar Lista dinamica empresareceptora 3 y 4
    Route::get('BandejaInversionista/{id}/eliminarSoporteDinamico','Planilla1DecInversionController@eliminarSoporte');



    Route::get('BandejaInversionista/{id}/eliminarAccionista','InversionistaExtController@eliminarAccionista');

    Route::get('BandejaInversionista/eliminarAccionista/{id}','InversionistaExtController@eliminarAccionista');


    /*Ruta PDF de la Solicitud Inversionista*/
    Route::get('/planillaSolInversionista', [
         'uses' => 'PdfController@planillaSolInversionista',
       ]);

      /*Ruta PDF de Recaudos*/
    Route::get('/planillaRecaudosInversionista', [
         'uses' => 'PdfController@planillaRecaudosInversionista',
       ]);

     /*Ruta PDF Certificado Inversionista*/

resources/views/consignatario/create.blade.php
@extends('templates/layoutlte')
@section('content')
{{Form::open(['route'=>'consignatario.store','method'=>'POST','id'=>'formconsig'])}}

<div class="panels">
<div class="row"> 
<div class="col-md-12">
	<div class="col-md-6">
	<div class="form-group">
			{!! Form::hidden('gen_usuario_id', Auth::user()->id) !!}
			{!! Form::label('Cartera','Cartera Comprador / Proveedor')!!}
			{!! Form::select('cat_tipo_cartera_id',$tipocartera,null,['class'=>'form-control','id'=>'cat_tipo_cartera_id',
			'placeholder'=>'Seleccione Comprador / Proveedor','onchange'=>'MostrarRif()']) !!}
		</div>
		<div class="form-group" id="rif" style="display:none;">
			{!! Form::label('consignatario','Rif Empresa')!!}
			{!! Form::text('rif_empresa',null,['class'=>'form-control','id'=>'rif_empresa','maxlength'=>'11','pattern'=>'^([VEJPG]{1})([-]{1})([0-9]{9})$'])!!}	
		</div>
		<div class="form-group">
			{!! Form::label('consignatario','Nombre o Razón Social')!!}
			{!! Form::text('nombre_consignatario',null,['class'=>'form-control','id'=>'nombre_consignatario','maxlength'=>'100','onkeypress'=>'return soloNumerosyLetras(event)'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('Contacto','Persona de Contacto')!!}
			{!! Form::text('perso_contac',null,['class'=>'form-control','id'=>'perso_contac','maxlength'=>'80','onkeypress'=>'return soloLetras(event)'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('Cargo','Cargo de la Persona de Contacto')!!}
			{!! Form::text('cargo_contac',null,['class'=>'form-control','id'=>'cargo_contac','maxlength'=>'60','onkeypress'=>'return soloLetras(event)'])!!}
		</div>		
		<div class="form-group" id="pais" style="display:none;">
			{!! Form::label('paises','País') !!}
			{!! Form::select('pais_id',$paises,null,['class'=>'form-control','id'=>'pais_id',
			'placeholder'=>'Seleccione un pais']) !!}
		</div>
	</div>
	<div class="col-md-6">
		<table style="width: 100%; display:none;" id="convenio">
			<tr>
				<td>
					<div class="form-group">
						{!! Form::label('conevio','Tipo de Convenio') !!}
						{!! Form::select('cat_tipo_convenio_id',$convenio,null,['class'=>'form-control','id'=>'cat_tipo_convenio_id',
						'placeholder'=>'Seleccione un Convenio']) !!}
					</div>
				</td>
				<td align="center">
					<a id="infoCOnvenios" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-info-sign text-info" aria-hidden="true" ></span></a>
				</td>
			</tr>
		</table>		
		<div class="form-group">
			{!! Form::label('ciudad','Ciudad')!!}
			{!! Form::text('ciudad_consignatario',null,['class'=>'form-control','id'=>'ciudad_consignatario','onkeypress'=>'return soloLetras(event)','maxlength'=>'100'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('direccion','Dirección')!!}
			{!! Form::text('direccion',null,['class'=>'form-control','id'=>'direccion','maxlength'=>'200'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('telefono','Teléfono de Contacto')!!}
			{!! Form::text('telefono_consignatario',null,['class'=>'form-control','id'=>'telefono_consignatario','onkeypress'=>'return soloNumeros(event)','maxlength'=>'17'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('email','Correo Electrónico')!!}
			{!! Form::text('correo',null,['class'=>'form-control','id'=>'correo','maxlength'=>'80'])!!}
		</div>
	</div>
</div>
</div>
<br><div class="row">
	<div class="col-md-12">
		<div class="col-md-4"></div>
		<div class="col-md-4 text-center">
		<a href="{{ route('consignatario.index') }}" class="btn btn-primary">Cancelar</a>
		<input type="submit" class="btn btn-success" value="Enviar" name="" onclick="validacionForm()">
		</div>
		<div class="col-md-4"></div>
	</div>
	</div>
	</div>
{{Form::close()}}
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Información de Convenios</h4>
      </div>
      <div class="modal-body">
            <table class="table table-bordered">
                <tbody>
                <tr class="bg-primary">
                    <th>ALADI</th>
                    <th>CAN</th>
                    <th>G3</th>
                    <th>SUCRE</th>
                    <th>MERCOSUR</th>
                </tr>
                <tr>
                    <td>
                    	Argentina <br>
						Bolivia  <br>
						Brasil <br>
						Chile <br>
						Colombia <br>
						Ecuador <br>
						Mexicanos <br>
						Paraguay <br>
						Perú <br>
						Uruguay <br>
						Venezuela <br>
                    </td>
                    <td>
	                    Bolivia <br>
						Colombia <br>
						Ecuador <br>
						Perú <br>
						Venezuela <br>
                    </td>
                    <td>
	                    México <br>
						Colombia <br>
						Venezuela <br>
                    </td>
                    <td>
	                    Bolivia <br>
						Cuba <br>
						Ecuador <br>
						Nicaragua <br>
						Venezuela <br>
                    </td>
                    <td>
	                    Argentina <br>
	                    Brasil <br>
						Paraguay <br>
						Venezuela <br>
                    </td>
                </tr>
              </tbody>
            </table>     
       </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-md-12">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
              <div class="form-group">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
            <div class="col-md-4"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- fin Modal -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="{{asset('js/ajax_v2.1.1.js')}}"></script>
<script type="text/javascript">
  	
	//Validación de formulario, se puede llamar y pasar la sección que contenga los inputs a validar

    	var error = '<div class="msg_alert"><span style="color:red" class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span><strong id="cod_aran-error" class="added"> El campo es obligatorio.</strong></div>';
		var valido = '<div class="msg_alert"><span style="color:green" class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span></div>';
		var mens = ['Estimado Usuario. Debe completar los campos solicitados', 'El campo RIF debe respetar el formato J-000000000, asegurese de colocar el guíon y todos los números de su rif']

		validacionForm = function() {

		$('#formconsig').submit(function(event) {
		
		var campos = $('#formconsig').find('input:text, select');
		var n = campos.length;
		var err = 0;

		$("div").remove(".msg_alert");
		//bucle que recorre todos los elementos del formulario
		for (var i = 0; i < n; i++) {
				var cod_input = $('#formconsig').find('input:text, select').eq(i);
				if (!cod_input.attr('noreq')) {
					if (cod_input.val() == '' || cod_input.val() == null)
					{
						err = 1;
						cod_input.css('border', '1px solid red').after(error);
					}
					else{
						if (err == 1) {err = 1;}else{err = 0;}
						cod_input.css('border', '1px solid green').after(valido);
					}
					
				}
		}

		if (!$("#rif_empresa").attr('noreq')) {
			if ($("#rif_empresa:contains('-')").val() || $("#rif_empresa").val().length < 11) {
				
				err = 2;

			}
		}

		//Si hay errores se detendrá el submit del formulario y devolverá una alerta
		if(err==1){
				event.preventDefault();
				swal("Por Favor!", mens[0], "warning")
			}

		//Si hay errores se detendrá el submit del formulario y devolverá una alerta
		if(err==2){
				event.preventDefault();
				swal("Por Favor!", mens[1], "warning")
			}

			});
		}
</script>

@stop

resources/views/consignatario/edit.blade.php
@extends('templates/layoutlte')
@section('content')
{{Form::model($consig,['route'=>['consignatario.update', $consig->id],'method'=>'PATCH','id'=>'formconsig'])}}
<br><div class="row"> 
<div class="col-md-12">
	<div class="col-md-6">
	<div class="form-group">
			{!! Form::hidden('gen_usuario_id', Auth::user()->id) !!}
			{!! Form::label('Cartera','Cartera Comprador / Proveedor')!!}
			{!! Form::select('cat_tipo_cartera_id',$tipocartera,null,['class'=>'form-control','id'=>'cat_tipo_cartera_id','placeholder'=>'Seleccione Comprador / Proveedor','onchange'=>'MostrarRif()']) !!}
		</div>
		<div class="form-group" id="rif" style="display:none;">
			{!! Form::label('consignatario','Rif Empresa')!!}
			{!! Form::text('rif_empresa',null,['class'=>'form-control','id'=>'rif_empresa','maxlength'=>'11','pattern'=>'^([VEJPG]{1})([-]{1})([0-9]{9})$'])!!}
					
		</div>
		<div class="form-group">
			{!! Form::label('consignatario','Nombre o Razón Social')!!}
			{!! Form::text('nombre_consignatario',null,['class'=>'form-control','id'=>'nombre_consignatario','maxlength'=>'100','onkeypress'=>'return soloNumerosyLetras(event)'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('Contacto','Persona de Contacto')!!}
			{!! Form::text('perso_contac',null,['class'=>'form-control','id'=>'perso_contac','maxlength'=>'80','onkeypress'=>'return soloLetras(event)'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('Cargo','Cargo de la Persona de Contacto')!!}
			{!! Form::text('cargo_contac',null,['class'=>'form-control','id'=>'cargo_contac','maxlength'=>'60','onkeypress'=>'return soloLetras(event)'])!!}
		</div>		
		<div class="form-group" id="pais" style="display:none;">
			{!! Form::label('paises','País') !!}
			{!! Form::select('pais_id',$paises,null,['class'=>'form-control','id'=>'pais_id',
			'placeholder'=>'Seleccione un pais']) !!}
		</div>
	</div>
	<div class="col-md-6">
			<table style="width: 100%; display:none;" id="convenio">
			<tr>
				<td>
					<div class="form-group">
						{!! Form::label('conevio','Tipo de Convenio') !!}
						{!! Form::select('cat_tipo_convenio_id',$convenio,null,['class'=>'form-control','id'=>'cat_tipo_convenio_id',
						'placeholder'=>'Seleccione un Convenio']) !!}
					</div>
				</td>
				<td align="center">
					<a id="infoCOnvenios" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-info-sign text-info" aria-hidden="true" ></span></a>
				</td>
			</tr>
		</table>
		<div class="form-group">
			{!! Form::label('ciudad','Ciudad')!!}
			{!! Form::text('ciudad_consignatario',null,['class'=>'form-control','id'=>'ciudad_consignatario','onkeypress'=>'return soloLetras(event)','maxlength'=>'100'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('direccion','Dirección')!!}
			{!! Form::text('direccion',null,['class'=>'form-control','id'=>'direccion','maxlength'=>'200'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('telefono','Teléfono de Contacto')!!}
			{!! Form::text('telefono_consignatario',null,['class'=>'form-control','id'=>'telefono_consignatario','onkeypress'=>'return soloNumeros(event)','maxlength'=>'17'])!!}
		</div>
		<div class="form-group">
			{!! Form::label('email','Correo Electrónico')!!}
			{!! Form::text('correo',null,['class'=>'form-control','id'=>'correo','maxlength'=>'80'])!!}
		</div>
	</div>
</div>
</div>
<br><div class="row">
	<div class="col-md-12">
		<div class="col-md-4"></div>
		<div class="col-md-4 text-center">
		<a href="{{ route('consignatario.index') }}" class="btn btn-primary">Cancelar</a>
		<input type="submit" class="btn btn-success" value="Enviar" name="" onclick="validacionForm()">
		</div>
		<div class="col-md-4"></div>
	</div>
</div>

{{Form::close()}}
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Información de Convenios</h4>
      </div>
      <div class="modal-body">
            <table class="table table-bordered">
                <tbody>
                <tr class="bg-primary">
                    <th>ALADI</th>
                    <th>CAN</th>
                    <th>G3</th>
                    <th>SUCRE</th>
                    <th>MERCOSUR</th>
                </tr>
                <tr>
                    <td>
                    	Argentina
						Bolivia
						Brasil
						Chile
						Colombia
						Ecuador
						Mexicanos
						Paraguay
						Perú
						Uruguay
						Venezuela
                    </td>
                    <td>
	                    Bolivia
						Colombia
						Ecuador
						Perú
						Venezuela
                    </td>
                    <td>
	                    México
						Colombia
						Venezuela
                    </td>
                    <td>
	                    Bolivia
						Cuba
						Ecuador
						Nicaragua
						Venezuela
                    </td>
                    <td>
	                    Argentina
	                    Brasil
						Paraguay
						Venezuela
                    </td>
                </tr>
            </tbody>
        </table>     
        </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-md-12">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
              <div class="form-group">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
            <div class="col-md-4"></div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<!-- fin Modal -->


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="{{asset('js/ajax_v2.1.1.js')}}"></script>

<script>
	$(document).ready(function(){
		MostrarRif();
	});
</script>

<script type="text/javascript">
  	
	//Validación de formulario, se puede llamar y pasar la sección que contenga los inputs a validar

    	var error = '<div class="msg_alert"><span style="color:red" class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span><strong id="cod_aran-error" class="added"> El campo es obligatorio.</strong></div>';
		var valido = '<div class="msg_alert"><span style="color:green" class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span></div>';
		var mens = ['Estimado Usuario. Debe completar los campos solicitados', 'El campo RIF debe respetar el formato J-000000000, asegúrese de colocar el guíon y todos los números de su rif']

		validacionForm = function() {

		$('#formconsig').submit(function(event) {
		
		var campos = $('#formconsig').find('input:text, select');
		var n = campos.length;
		var err = 0;

		$("div").remove(".msg_alert");
		//bucle que recorre todos los elementos del formulario
		for (var i = 0; i < n; i++) {
				var cod_input = $('#formconsig').find('input:text, select').eq(i);
				if (!cod_input.attr('noreq')) {
					if (cod_input.val() == '' || cod_input.val() == null)
					{
						err = 1;
						cod_input.css('border', '1px solid red').after(error);
					}
					else{
						if (err == 1) {err = 1;}else{err = 0;}
						cod_input.css('border', '1px solid green').after(valido);
					}
					
				}
		}
		if (!$("#rif_empresa").attr('noreq')) {
			if ($("#rif_empresa:contains('-')").val() || $("#rif_empresa").val().length < 11) {
				
				err = 2;

			}
		}

		//Si hay errores se detendrá el submit del formulario y devolverá una alerta
		if(err==1){
				event.preventDefault();
				swal("Por Favor!", mens[0], "warning")
			}

		//Si hay errores se detendrá el submit del formulario y devolverá una alerta
		if(err==2){
				event.preventDefault();
				swal("Por Favor!", mens[1], "warning")
			}

			});
		}
</script>

@stop