routes/web.php
    Route::resource('DJOPlanilla3','DJOPlanilla3Controller');
    Route::resource('DJOPlanilla4','DJOPlanilla4Controller');
    Route::resource('DJOPlanilla5','DJOPlanilla5Controller');
    Route::resource('DJOPlanilla6','DJOPlanilla6Controller');
    /***********ruta resource para el certificado de origen *************/
    Route::resource('CertificadoOrigen','CertificadoController');
    Route::get('CertificadoOrigen/{id}/eliminarRegistroProd','CertificadOrigenController@deleteProducto');
    Route::get('CertificadoOrigen/{id}/eliminarRegistroCriterio','CertificadOrigenController@deleteCriterio');
    /********CAMBIO DE CONTRASEÑA**************/
    Route::resource('CambioContrasena','CambioContrasenaController');
    /********CAMBIO PREGUNTA DE SEGURIDAD**************/
    /*Route::get('/cambioPreguntaSeguridad', function(){

        return view('usuario.forms.cambioPreguntaSeguridad')->with('titulo','Cambio de Pregunta de Seguridad')->with('descripcion','Datos de Pregunta de Seguridad');

    });*/

    /*Route::post('/actualizarempresa', [
        'uses' => 'HomeController@accionform1'
    ]);
    */
    /********REGISTRO DE CONSIGNATARIO**************/
    Route::resource('consignatario','RegistroConsignatarioController');
    /********REGISTRO DE AGENTE ADUANAL**************/
    Route::resource('AgenteAduanal','AgenteAduanalController');
    /********REGISTRO DE DUA**************/
    Route::resource('Dua', 'DuaController');
    /********REGISTRO DE FACTURA**************/
    /********CAMBIO PREGUNTA DE SEGURIDAD*******/
     Route::resource('CambioPregunta','CambioPreSegController');
   /****************Registro de Factura -Productos***************/
    Route::resource('factura','GenFacturaController');
    Route::resource('productos','DetProdFacturaController');
    Route::get('productos/{id}/eliminar','DetProdFacturaController@eliminar');
    /******************** Routes Facturas -Tecnologia ****************************/
    Route::get('productos_tecno/{id}/eliminar','DetProdTecnologiaController@eliminar');
    Route::get('verificarFac','TipoSolicitudController@verificarFac');
    Route::resource('productos_tecno','DetProdTecnologiaController');
    /********REGISTRO DE PERMISO**************/
    Route::resource('Permisos','PermisoController');
    Route::resource('ProdutPermisos','ProdutPermisosController');
    Route::get('ProdutPermisos/{id}/eliminar','ProdutPermisosController@eliminar');
    /*****************************************/
     /********REGISTRO DE Nota de Credito**************/

    Route::resource('NCredito','NCreditoController');

     Route::get('/facturaNC', [
         'uses' => 'NCreditoController@facturaNC',

     ]);

    /************************************************/
    /********REGISTRO DE Nota de Debito**************/

    Route::resource('NDebito','NdebitoController');

     Route::get('/facturaND', [
         'uses' => 'NdebitoController@facturaND',

     ]);
    /********ANTICIPO DE EXPORTACION**************/
    /*Route::get('/datosempresa', function(){



    /********ANTICIPO DE EXPORTACION**************/
    Route::resource('Anticipo','GenAnticipoController');


    /********REGISTRO DE EXPORTACION**************/
    Route::resource('SolicitudER','TipoSolicitudController');
    Route::resource('FacturaSolicitud','FacturaSolicitudController');
    Route::get('FacturaSolicitud/{id}/eliminar','FacturaSolicitudController@eliminar');
    Route::resource('','FacturaSolicitudController');
    Route::get('factura-solicitud/{id}/delete-er', 'FacturaSolicitudController@deleteEr')->name('factura-solicitud.delete-er');
   


    /********REGISTRO DE EXPORTACION Financiamiento Solicitud**************/
    Route::resource('FinanciamientoSolicitud','FinancSolicitudController');
    Route::get('FinanciamientoSolicitud/{id}/edit','FinancSolicitudController@edit');

    Route::resource('productos_export','ProductosController');
    Route::get('productos_export/{id}/eliminar','ProductosController@eliminar');
    Route::get('productos_export/{id}/editar','ProductosController@editar');
    Route::POST('actualizar',[
        'uses'=>'ProductosController@actualizar',
        'as'=> 'productos_export_edit.actualizar'
    ]);


    /******************************************************************************/

    /************************Registro de DVD**************************************/

    Route::resource('DvdSolicitud','GenDVDSolicitudController');
    Route::resource('ListaVenta','ListaVentaController');
    Route::resource('VentaSolicitud','VentaSolicitudController');





    /**************************Documentos de DVD*************************************/

    Route::resource('DocumentosDVD','DocumentosDVDController');
    Route::get('documentos-dvd/{id}/delete-dvd', 'DocumentosDVDController@deleteDvd')->name('documentos-dvd.delete-dvd');


    //Ruta para  Eliminar Lista dinamica Doc 2 y 4
    Route::get('DocumentosDVD/{id}/eliminarDocDvd','DocumentosDVDController@eliminarDocDvd');



    Route::resource('ListaVentaND','ListaVentaNDController');

    Route::resource('VentanND','VentaNDController');


    Route::resource('DvdSolicitudND','ListaVentaNDController');



    /**************************Documentos de DVD*************************************/

    Route::resource('DocumentosDvdND','DocumentosDvdNDController');


    //Ruta para  Eliminar Lista dinamica Doc 2 y 4
    Route::get('DocumentosDvdND/{id}/eliminarDocND','DocumentosDvdNDController@eliminarDocND');






    /*************************Reportar dudas o Problemas***************************/
    Route::resource('Dudas','DudasController');
    
    Route::post('Dudas/delete/{id}',[
        'uses' => 'DudasController@destroy'
    ]);

    Route::put('Dudas/update/{id}',[
        'uses' => 'DudasController@update'
    ]);

    Route::get('Dudas/{gen_asistencia_usuario_id}',[
        'uses' => 'DudasController@edit'
    ]);

    /*inversionista extranjera*/
    Route::resource('BandejaInversionista','InversionistaExtController');//

     Route::POST('FormInversionista',[
        'uses'=>'InversionistaExtController@RedireccionarForm',
        'as'=> 'BandejaInversionista.FormInversionista'
    ]);
     //Para cuando falla el Vali
      Route::get('FormInversionista',[
        'uses'=>'InversionistaExtController@RedireccionarForm',
        'as'=> 'BandejaInversionista.FormInversionista'
    ]);



    Route::get('BandejaInversionista/ActividadEcoInversionista/{id}', [
        'uses' => 'InversionistaExtController@ActividadEcoEmpnIvert'
    ]);





    //Ruta para  Eliminar Lista dinamica Doc 2 y 4
    Route::get('BandejaInversionista/{id}/eliminarSoporte2','InversionistaExtController@eliminarSoporte');

    /////////////////////////////////////////////////////////////

      //Ruta para  Eliminar Lista dinamica empresareceptora 3 y 4
    Route::get('BandejaInversionista/{id}/eliminarSoporteDinamico','Planilla1DecInversionController@eliminarSoporte');



    Route::get('BandejaInversionista/{id}/eliminarAccionista','InversionistaExtController@eliminarAccionista');

    Route::get('BandejaInversionista/eliminarAccionista/{id}','InversionistaExtController@eliminarAccionista');


    /*Ruta PDF de la Solicitud Inversionista*/
    Route::get('/planillaSolInversionista', [
         'uses' => 'PdfController@planillaSolInversionista',
       ]);

      /*Ruta PDF de Recaudos*/
    Route::get('/planillaRecaudosInversionista', [
         'uses' => 'PdfController@planillaRecaudosInversionista',
       ]);

     /*Ruta PDF Certificado Inversionista*/
    Route::get('/CertificadoInversionista', [
         'uses' => 'PdfController@CertificadoInversionista',
       ]);
    /*Certificado de Declaracion de Inversiones*/
    Route::get('/CertificadoInversionRealizada',[
    'uses'=>'PdfController@CertificadoInversionRealizada',
    ]);

    /*CertificadoRegistroVuce*/
    Route::get('/CertificadoRegistroVuce',[
        'uses'=>'PdfController@CertificadoRegistroVuce',
    ]);



/*Certificado de Declaracion de Inversiones*/
    Route::get('/CertificadoInversionRealizadaDJIR',[
            'uses'=>'PdfController@CertificadoInversionRealizada',
     ]);


    /*Declaracion de Inversion Planilla 1*/
    Route::get('/DeclaracionJuradaInversionRealizadaP01',[
        'uses'=>'PdfController@DeclaracionJuradaInversionRealizadaP01',
    ]);

    /*Fin de la ruta de declaracion planilla 1*/



        /*Declaracion de Inversion Planilla 2*/
    Route::get('/DeclaracionJuradaInversionRealizadaP02',[
        'uses'=>'PdfController@DeclaracionJuradaInversionRealizadaP02',
    ]);

    /*Fin de la ruta de declaracion planilla 2*/




     /*Declaracion de Inversion Planilla 3*/
    Route::get('/DeclaracionJuradaInversionRealizadaP03',[
        'uses'=>'PdfController@DeclaracionJuradaInversionRealizadaP03',
    ]);







    /*inversion extranjera*/
    Route::resource('BandejaInversion','BandejaInversionController');

     ///////////Ruta para Declaración de Inversión//////////
       Route::POST('FormDeclaracionInversion',[
        'uses'=>'BandejaInversionController@RedirecFormDeclaracionInversion',
        'as'=> 'BandejaInversion.FormDeclaracionInversion'
    ]);
     //Para cuando falla el Validation
    Route::get('FormDeclaracionInversion',[
        'uses'=>'BandejaInversionController@RedirecFormDeclaracionInversion',
        'as'=> 'BandejaInversion.FormDeclaracionInversion'
    ]);

     //Para cuando esta incompleta
    Route::get('FormDeclaracionInversion/{gen_declaracion_inversion_id}',[
        'uses'=>'BandejaInversionController@RedirecFormDeclaracionInversionComplet',
        'as'=> 'BandejaInversion.FormDeclaracionInversionComplet'
    ]);


app/Models/FacturaSolicitud.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FacturaSolicitud extends Model
{
    protected $table='factura_solicitud';

    protected $fillable =[

     'id',
     'gen_factura_id',
     'gen_solicitud_id',
     'numero_nota_credito',
     'bactivo',
    ]; 

  public function factura(){
     
     return $this->hasOne('App\Models\GenFactura','id','gen_factura_id');
  }

    /*public function solicitud() {

     return $this->hasMany('App\Models\GenSolicitud','id','gen_solicitud_id');

    }*/
  public function solicitud(){
     
     return $this->hasOne('App\Models\GenSolicitud','id','gen_solicitud_id');
  }

}

resources/views/FacturaSolicitud/create.blade.php
@extends('templates/layoutlte')
@section('content')
{{Form::open(['route'=>'FacturaSolicitud.store','method'=>'POST','id'=>'add_numfactura','onSubmit'=>"return validar_facturas(this);"]) }}
<!--{{Form::hidden('metodo','Crear')}}!-->
@php $contador=count($factsolicitud); @endphp<!--Cree una etiqiueta php para con un contador!-->
{{Form::hidden('contador',$contador)}}<!--Campo oculto!-->

  <!-- Pestañas -->
  <div class="warpper">
    <input class="radio" id="one" name="group" type="radio" checked>
    <input class="radio" id="two" name="group" type="radio">
    <input class="radio" id="three" name="group" type="radio">
    <div class="tabs">
      <label class="tab" id="one-tab" for="one">Facturas asociadas</label>

    </div>
    <div class="panels">
      <div class="panel" id="one-panel">
<br>
<div class="row">
	<div class="col-md-12">
		<div class="col-md-2"></div>
		<div class="col-md-6">
			<div class="form-group">
			<table class="table table-bordered" id="fieldsfac" style="border: 0px solid ">
					<tr>
					<td colspan="4">
					{!! Form::label('tsolicitud','Tipo de Solictud')!!}
					{!! Form::select('tipo_solicitud_id',$tiposolic,null,['class'=>'form-control','id'=>'tipo_solicitud_id','onchange'=>'tiposolictud()']) !!}

					</td>
			     	</tr>
					<tr>
					<td colspan="2">{!! Form::label('asociadas','Facturas Asociadas')!!}</td>
					<td>
						<button  name="add" type="button" id="add" value="add more" class="btn btn-success">Agregar</button></td>
					</tr>
                    <tr>
			
           @if (isset($factsolicitud))
					<tr id="">
						<td>{!!Form::label('','Número de Factura')!!}{!!Form::select('gen_factura_id[]',$factsolicitud,null,['placeholder'=>'--Seleccione Una Factura--','class'=>'form-control grupos_facturas','id'=>'gen_factura_id0','onchange'=>"numeroNotaCredi(this.value,0)"]) !!}</td>
						<td>{!!Form::label('','Número nota Crédito')!!}{!! Form::text('numero_nota_credito[]',null,['class'=>'form-control nota','readonly'=>'readonly','id'=>'numero_nota_credito0']) !!}</td>{{Form::hidden('gen_nota_credito_id[]',null,['class'=>'form-control','readonly'=>'readonly','id'=>'gen_nota_credito_id0'])}}<td><br><button  name="remove" type="button" id="" value="" class="btn btn-danger btn-remove" >x</button></td>
					</tr>

				    @endif
				</table>
				</div>
			</div>
		</div>

		<br>
		<div class="row">
			<div class="col-md-12">
				<div class="col-md-4"></div>
				<div class="col-md-4 text-left">
					<!--a href="{{ route('SolicitudER.create') }}" class="btn btn-primary">Regresar</!--a -->
					<button href="#" class="btn btn-success"  value="Continuar"  name="" >Continuar</button>
				</div>
				<div class="col-md-4"></div>
			</div>
		</div>
		{{Form::close()}}

<!--script inicio!-->
<script src="{{asset('js/ajax_v2.1.1.js')}}"></script>

<script type="text/javascript">


var item_dua=null;
var duas=[];
var facturas=[];


	 @foreach($duas as $key=> $data)
	    @if($data!=null){
      duas[{{$key}}]={{$data}};
		}
		@endif
	 @endforeach

onloadFacturas();
$(document).ready(function(){
var x = $('input[name="contador"]').val();
//var i=parseInt(x);
var i=0;
var table = 1;
var total={{count($factsolicitud)}};

$('#add').click(function(){
     i++;
	 if (total >= 0 && (total == 0 || table < total)) {
	
    @php
    	$auxI = "<script>document.write(i)</script>";	
    	//dd($factsolicitud);
    @endphp
    $('#fieldsfac tr:last').after('<tr id="row'+i+'" display="block" class="show_div"><td><select class="form-control grupos_facturas" id="gen_factura_id'+i+'" onchange="numeroNotaCredi(this.value,'+i+')" name="gen_factura_id[]"><option value="">--Seleccione Una Factura--</option>@foreach ($factsolicitud as $key => $element)<option value="{{$key}}">{{$element}}</option>@endforeach</select></td><td><input type="text" name="numero_nota_credito[]" class="form-control nota" id="numero_nota_credito'+i+'" readonly="readonly"></td><td style="display: none"><input type="text" name="gen_nota_credito_id[]" class="form-control" id="gen_nota_credito_id'+i+'" readonly="readonly"></td><td><button  name="remove" type="button" id="'+i+'" value="" class="btn btn-danger btn-remove">x</button></td></tr>');
		 table++;
	}else{
	swal("Denegada", "Ya alcanzó el máximo de facturas registradas", "warning");
	}

onloadFacturas();

  });


	$(document).on('click','.btn-remove',function(){
			var id_boton= $(this).attr("id");
			table--;
			$("#row"+id_boton+"").remove();

	});


});


	function onloadFacturas(){

 	   var select=document.getElementsByTagName('select');

 		 for (var i = 0; i < select.length; i++) {
			 select[i].removeEventListener('change',function(){});

 		 	 select[i].addEventListener('change',function(){

 				   validar_facturas(this);
 			});

 		 }
  }


function validar_facturas(element){
	var ret = true;
	var aux=false;
	var auxIndex;
	var empty=0;

	if(!element==false){


				var selects = element.parentNode.parentNode.parentNode.parentNode.parentNode.getElementsByTagName('select');

				if(!selects==false){

					facturas=[];
					 item_dua=null;
					for(var i = 0; i<=selects.length-1; i++){

						if(selects[i].value==""){

							    empty++;
									ret = false;
						}

						if(empty>=1){
							swal("Denegada", "Debe seleccionar una opción para continuar",'warning');

						}


						facturas.forEach(function(value,index,arr){
							if(value===selects[i].value){
							aux=true;
							swal("Denegada", "Las Facturas deben ser diferentes",'warning');
							selects[i].selectedIndex=0;
							}
						});

						if(!aux && selects[i].value!="")
						facturas.push(selects[i].value);
						else {
							ret = false;
						}


							//console.log(facturas);

if(selects[i].value!=""){
							if(item_dua==null ){
								item_dua = duas[selects[i].value];
							}else{

								if(duas[selects[i].value]!=item_dua){
									swal("Denegada", "Las Facturas deben tener la misma dua",'warning');

									auxIndex = facturas.indexOf(selects[i].value);
									if(auxIndex>-1){
										facturas.splice(auxIndex,1);
									}
									//console.log(facturas);

									    selects[i].selectedIndex=0;
											ret = false;
								}

							}
							}
					}


				}


		}

		return ret;
}

function numeroNotaCredi(valor,num){//alert(num);

	/*var select=document.getElementsByTagName('select');
    for (var i = 0; i < select.length; i++) {
	    var Val=$("#gen_factura_id"+i).val();        			
	    
	           			
   	}	*/					
							 //num_nota[i].value(numero);
	

		$.ajax({   
	            url: '/exportador/factura/'+valor,
	            type: 'GET',
	            

	            data: {
	                    '_token'  : $('#token').val(),  
	                    
	                },
	       
	        })

	        .done(function(data) {
	        	
	        	console.log('data',data);
	        	/*if (data.length == 0 ) {
	        		$('#numero_nota_credito'+num).val(0);
	        	}*/
	           // alert(data);
	           let notas_credito = '';
	           let notas_id = '';
	            //if (isset(data)) {
	            if (data.length !== 0) {
	            	$.each(data, function(index, val) {
		            	//var numero     = data.numero_nota_credito;
		            	//var nota_credito_id     = data.id;
		            	//alert(nota_credito_id);
		            	// console.log('val.numero_nota_credito', val.numero_nota_credito);
		            	 notas_credito += val.numero_nota_credito+', ';
		            	 //val.numero_nota_credito.concat(',', val.numero_nota_credito);
		            	 notas_id     += val.id+',';
		            			//alert(num);
		            			
		            	//console.log('val.numero_nota_credito', notas_credito);		
		            				    //$('#numero_nota_credito'+num).val(numero);
		            					//$('#gen_nota_credito_id'+num).val(nota_credito_id);
		            			
		            });
		            
		            console.log('val.numero_nota_credito', notas_credito);
		            $('#numero_nota_credito'+num).val(notas_credito);	
		            $('#gen_nota_credito_id'+num).val(notas_id.substr(0, notas_id.length - 1));	
	            } else {
	            	$('#numero_nota_credito'+num).val(0);
	            }
	            		
		            		//	alert(a);
		            			//console.log(a);
					 		
		            	//
	            	//}
	            /*}else{
	            	$('#valor').val(0);
	            }*/
	            



	           
	    })

	    .fail(function(jqXHR, textStatus, thrownError) {
	        errorAjax(jqXHR,textStatus);
	    })

   
}
</script><!--Fin del script-->
</div>
@stop